@Products.Source_HostAddress = http://localhost:5152

GET {{Products.Source_HostAddress}}/todos/
Accept: application/json

###

GET {{Products.Source_HostAddress}}/todos/1
Accept: application/json

###
